from fastapi import APIRouter
from app.api.v1 import auth, dashboard, transactions, documents, ai_assistant, categories, suppliers, customers, approvals, events, audit, settings, companies, webhooks, reports, bank_reconciliation, fiscal, category_groups, settlements, bank_accounts, chart_templates, invitations, transaction_lines

api_router = APIRouter()

api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(companies.router, prefix="/companies", tags=["companies"])
api_router.include_router(dashboard.router, prefix="/dashboard", tags=["dashboard"])
api_router.include_router(transactions.router, prefix="/transactions", tags=["transactions"])
api_router.include_router(settlements.router, prefix="/transactions", tags=["settlements"])
api_router.include_router(transaction_lines.router, prefix="/transactions", tags=["lines"])
api_router.include_router(bank_accounts.router, prefix="/bank-accounts", tags=["bank-accounts"])
api_router.include_router(documents.router, prefix="/documents", tags=["documents"])
api_router.include_router(ai_assistant.router, prefix="/ai", tags=["ai"])
api_router.include_router(category_groups.router, prefix="/category-groups", tags=["categories"])
api_router.include_router(chart_templates.router, prefix="/chart-templates", tags=["categories"])
api_router.include_router(invitations.router, prefix="/invitations", tags=["team"])
api_router.include_router(categories.router, prefix="/categories", tags=["categories"])
api_router.include_router(suppliers.router, prefix="/suppliers", tags=["suppliers"])
api_router.include_router(customers.router, prefix="/customers", tags=["customers"])
api_router.include_router(approvals.router, prefix="/approvals", tags=["approvals"])
api_router.include_router(events.router, prefix="/events", tags=["events"])
api_router.include_router(audit.router, prefix="/audit", tags=["audit"])
api_router.include_router(settings.router, prefix="/settings", tags=["settings"])
api_router.include_router(webhooks.router, prefix="/webhooks", tags=["webhooks"])
api_router.include_router(reports.router, prefix="/reports", tags=["reports"])
api_router.include_router(bank_reconciliation.router, prefix="/bank", tags=["bank"])
api_router.include_router(fiscal.router, prefix="/fiscal", tags=["fiscal"])
