"""Team and multi-company: invitations, account type, membership uniqueness

Adds the SaaS layer: a login can belong to several companies, and people can be
invited into one. Existing rows are backfilled with server defaults so the
upgrade is safe on a database that already has users.

Revision ID: 0002_team
Revises: 0001_baseline
Create Date: 2026-09-01 18:39:15.149014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_team'
down_revision: Union[str, Sequence[str], None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('invited_by', sa.String(), nullable=True),
    sa.Column('accepted_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitations_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_token'), ['token'], unique=True)

    # Backfill first: every existing membership predates invitations.
    with op.batch_alter_table('user_memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invited_by', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_memberships_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_memberships_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_membership_user_company', ['user_id', 'company_id'])
        batch_op.create_foreign_key('fk_membership_invited_by', 'users', ['invited_by'], ['id'])

    # Everyone who existed before invitations registered on their own, so they
    # are "full" accounts and stay active. The server defaults do the backfill.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.String(), nullable=False,
                                      server_default='full'))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True,
                                      server_default=sa.true()))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('active')
        batch_op.drop_column('account_type')

    with op.batch_alter_table('user_memberships', schema=None) as batch_op:
        batch_op.drop_constraint('fk_membership_invited_by', type_='foreignkey')
        batch_op.drop_constraint('uq_membership_user_company', type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_memberships_company_id'))
        batch_op.drop_column('invited_by')

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_token'))
        batch_op.drop_index(batch_op.f('ix_invitations_id'))
        batch_op.drop_index(batch_op.f('ix_invitations_email'))
        batch_op.drop_index(batch_op.f('ix_invitations_company_id'))

    op.drop_table('invitations')
    # ### end Alembic commands ###
