"""Reconciliation: statement money as Numeric, payments linked to bank lines

The statement is what every other number gets checked against, so it stops
being the one place holding money in floating point. Existing rows are
converted in place by the batch rebuild; a payment now records the bank line
that proves it, and whether it was created from one.

Revision ID: 0003_reconciliation
Revises: 0002_team
Create Date: 2026-09-01 19:05:58.455104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_reconciliation'
down_revision: Union[str, Sequence[str], None] = '0002_team'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_statement_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reconciled_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
        batch_op.alter_column('balance',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)

    # Values that came in as floats may carry more than two decimals; the
    # column is cents now, so make the data say so too.
    op.execute("UPDATE bank_statement_entries SET amount = ROUND(amount, 2)")
    op.execute("UPDATE bank_statement_entries SET balance = ROUND(balance, 2) WHERE balance IS NOT NULL")

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_entry_id', sa.String(), nullable=True))
        # Existing payments were all registered by hand.
        batch_op.add_column(sa.Column('source', sa.String(), nullable=True,
                                      server_default='manual'))
        batch_op.create_index(batch_op.f('ix_payments_bank_entry_id'), ['bank_entry_id'], unique=False)
        batch_op.create_foreign_key('fk_payment_bank_entry', 'bank_statement_entries', ['bank_entry_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payment_bank_entry', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payments_bank_entry_id'))
        batch_op.drop_column('source')
        batch_op.drop_column('bank_entry_id')

    with op.batch_alter_table('bank_statement_entries', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('reconciled_at')

    # ### end Alembic commands ###
