"""Invoice lines: mixed VAT rates within one document

Additive only: a transaction without lines keeps behaving exactly as before.

Revision ID: 0004_invoice_lines
Revises: 0003_reconciliation
Create Date: 2026-09-01 23:10:39.810456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004_invoice_lines'
down_revision: Union[str, Sequence[str], None] = '0003_reconciliation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_lines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Float(), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vat_exemption_reason', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_lines_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_lines_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_lines_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_lines_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_lines_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_lines_company_id'))

    op.drop_table('transaction_lines')
    # ### end Alembic commands ###
