"""Entities: one counterparty for supplier and customer

Folds the existing suppliers and customers into a single table, matching them
by NIF (and by name when the NIF is a placeholder) so a company that is both
becomes one row carrying both roles. The old tables are left in place: nothing
reads them after this, and keeping them makes the migration reversible.

Revision ID: 0005_entities
Revises: 0004_invoice_lines
Create Date: 2026-09-01 23:18:34.914599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005_entities'
down_revision: Union[str, Sequence[str], None] = '0004_invoice_lines'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nif', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('is_supplier', sa.Boolean(), nullable=True),
    sa.Column('is_customer', sa.Boolean(), nullable=True),
    sa.Column('default_category_id', sa.String(), nullable=True),
    sa.Column('default_category_name', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_nif'), ['nif'], unique=False)

    # Fold the two old tables in. Matching is by normalised NIF, falling back
    # to a normalised name when the NIF is missing or a placeholder, so the
    # same company does not end up as two entities.
    conn = op.get_bind()

    def _key(nif, name):
        clean = "".join(ch for ch in (nif or "") if ch.isdigit())
        if clean and clean not in ("000000000", "500000000"):
            return "nif:" + clean
        return "name:" + (name or "").strip().lower()

    seen: dict = {}

    for row in conn.execute(sa.text(
        "SELECT id, company_id, name, nif, email, phone, address, "
        "default_category_id, default_category_name FROM suppliers"
    )).mappings():
        key = (row["company_id"], _key(row["nif"], row["name"]))
        seen[key] = {
            "id": "ENT-" + row["id"],
            "company_id": row["company_id"],
            "name": row["name"],
            "nif": row["nif"],
            "email": row["email"],
            "phone": row["phone"],
            "address": row["address"],
            "is_supplier": True,
            "is_customer": False,
            "default_category_id": row["default_category_id"],
            "default_category_name": row["default_category_name"],
            "source_ref": "supplier:" + row["id"],
        }

    for row in conn.execute(sa.text(
        "SELECT id, company_id, name, nif, email, phone, "
        "default_category_id, default_category_name FROM customers"
    )).mappings():
        key = (row["company_id"], _key(row["nif"], row["name"]))
        existing = seen.get(key)
        if existing:
            # Same company on both sides: one entity, both roles.
            existing["is_customer"] = True
            existing["email"] = existing["email"] or row["email"]
            existing["phone"] = existing["phone"] or row["phone"]
            existing["source_ref"] = existing["source_ref"] + "+customer:" + row["id"]
            continue
        seen[key] = {
            "id": "ENT-" + row["id"],
            "company_id": row["company_id"],
            "name": row["name"],
            "nif": row["nif"],
            "email": row["email"],
            "phone": row["phone"],
            "address": None,
            "is_supplier": False,
            "is_customer": True,
            "default_category_id": row["default_category_id"],
            "default_category_name": row["default_category_name"],
            "source_ref": "customer:" + row["id"],
        }

    for entity in seen.values():
        conn.execute(sa.text(
            "INSERT INTO entities (id, company_id, name, nif, email, phone, address, "
            "is_supplier, is_customer, default_category_id, default_category_name, "
            "active, source_ref) VALUES (:id, :company_id, :name, :nif, :email, :phone, "
            ":address, :is_supplier, :is_customer, :default_category_id, "
            ":default_category_name, 1, :source_ref)"
        ), entity)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_nif'))
        batch_op.drop_index(batch_op.f('ix_entities_id'))
        batch_op.drop_index(batch_op.f('ix_entities_company_id'))

    op.drop_table('entities')
    # ### end Alembic commands ###
