"""Recurrences: rules for what repeats

The is_recurring flag existed and nothing acted on it; this is the rule and
its generated occurrences.

Revision ID: 0006_recurrences
Revises: 0005_entities
Create Date: 2026-09-01 23:25:22.460053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006_recurrences'
down_revision: Union[str, Sequence[str], None] = '0005_entities'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurrences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('entity_name', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('lead_days', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('last_generated_period', sa.String(), nullable=True),
    sa.Column('last_generated_at', sa.DateTime(), nullable=True),
    sa.Column('occurrences_created', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurrences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurrences_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurrences_id'), ['id'], unique=False)

    op.create_table('recurrence_occurrences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('recurrence_id', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('due_date', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['recurrence_id'], ['recurrences.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurrence_occurrences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurrence_occurrences_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurrence_occurrences_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurrence_occurrences_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurrence_occurrences_recurrence_id'), ['recurrence_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurrence_occurrences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurrence_occurrences_recurrence_id'))
        batch_op.drop_index(batch_op.f('ix_recurrence_occurrences_period'))
        batch_op.drop_index(batch_op.f('ix_recurrence_occurrences_id'))
        batch_op.drop_index(batch_op.f('ix_recurrence_occurrences_company_id'))

    op.drop_table('recurrence_occurrences')
    with op.batch_alter_table('recurrences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurrences_id'))
        batch_op.drop_index(batch_op.f('ix_recurrences_company_id'))

    op.drop_table('recurrences')
    # ### end Alembic commands ###
