"""Add entity fields and items

Revision ID: dea9622df654
Revises: 0009_cost_centers
Create Date: 2026-09-02 15:15:52.622525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dea9622df654'
down_revision: Union[str, Sequence[str], None] = '0009_cost_centers'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('ean', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('vat_rate', sa.String(), nullable=True),
    sa.Column('price_1', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('price_2', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('price_3', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('price_includes_vat', sa.Boolean(), nullable=True),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('financial_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('transport_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('customs_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('other_costs', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_estimated_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('service_group', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_id'), ['id'], unique=False)

    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_account', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contact_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contact_role', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mobile', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contact_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_taxable', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('vat_cash_regime', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_vat_exempt', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('address_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('discharge_address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('document_observations', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('internal_observations', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('auto_invoicing', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('model_10', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('accept_ad_emails', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_column('accept_ad_emails')
        batch_op.drop_column('model_10')
        batch_op.drop_column('auto_invoicing')
        batch_op.drop_column('internal_observations')
        batch_op.drop_column('document_observations')
        batch_op.drop_column('discharge_address')
        batch_op.drop_column('country')
        batch_op.drop_column('city')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('address_name')
        batch_op.drop_column('is_vat_exempt')
        batch_op.drop_column('vat_cash_regime')
        batch_op.drop_column('is_taxable')
        batch_op.drop_column('contact_type')
        batch_op.drop_column('website')
        batch_op.drop_column('mobile')
        batch_op.drop_column('contact_role')
        batch_op.drop_column('contact_name')
        batch_op.drop_column('sub_account')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_id'))
        batch_op.drop_index(batch_op.f('ix_items_company_id'))
        batch_op.drop_index(batch_op.f('ix_items_code'))

    op.drop_table('items')
    # ### end Alembic commands ###
